default:
  metrics:
    metrics-default:
      plugin: metrics-default
      enabled: false
  logging:
    logging-default:
      plugin: logging-default
      enabled: true
  events:
    events-default:
      plugin: events-default
      enabled: true
  services:
    service-default0X:
      plugin: service-default0
      enabled: true
      config:
        testa: 5
        testb: 6
    service-default1X:
      plugin: service-default1
      enabled: true
    service-default2X:
      plugin: service-default2
      enabled: true
    service-default3X:
      plugin: service-default3
      enabled: true
    service-default4X:
      plugin: service-default4
      enabled: true
